import { loader } from "fumadocs-core/source";
import { docs } from "../.source/server";

// `.source` is generated by fumadocs-mdx from content/docs/*.mdx — see
// source.config.ts. One loader, one tree, used by both the sidebar and the
// static search index below.
export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
